// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerInputHandler(ReducerEventContext ctx, DbVector3 position, DbQuaternion rotation, DbVector3 velocity, DbVector3 angularVelocity);
        public event UpdatePlayerInputHandler? OnUpdatePlayerInput;

        public void UpdatePlayerInput(DbVector3 position, DbQuaternion rotation, DbVector3 velocity, DbVector3 angularVelocity)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerInput(position, rotation, velocity, angularVelocity), this.SetCallReducerFlags.UpdatePlayerInputFlags);
        }

        public bool InvokeUpdatePlayerInput(ReducerEventContext ctx, Reducer.UpdatePlayerInput args)
        {
            if (OnUpdatePlayerInput == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdatePlayerInput(
                ctx,
                args.Position,
                args.Rotation,
                args.Velocity,
                args.AngularVelocity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerInput : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbQuaternion Rotation;
            [DataMember(Name = "velocity")]
            public DbVector3 Velocity;
            [DataMember(Name = "angularVelocity")]
            public DbVector3 AngularVelocity;

            public UpdatePlayerInput(
                DbVector3 Position,
                DbQuaternion Rotation,
                DbVector3 Velocity,
                DbVector3 AngularVelocity
            )
            {
                this.Position = Position;
                this.Rotation = Rotation;
                this.Velocity = Velocity;
                this.AngularVelocity = AngularVelocity;
            }

            public UpdatePlayerInput()
            {
                this.Position = new();
                this.Rotation = new();
                this.Velocity = new();
                this.AngularVelocity = new();
            }

            string IReducerArgs.ReducerName => "UpdatePlayerInput";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePlayerInputFlags;
        public void UpdatePlayerInput(CallReducerFlags flags) => UpdatePlayerInputFlags = flags;
    }
}
