// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ship
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "player_id")]
        public uint PlayerId;
        [DataMember(Name = "rotation")]
        public DbQuaternion Rotation;
        [DataMember(Name = "position")]
        public DbVector3 Position;
        [DataMember(Name = "velocity")]
        public DbVector3 Velocity;
        [DataMember(Name = "angularVelocity")]
        public DbVector3 AngularVelocity;
        [DataMember(Name = "last_split_time")]
        public SpacetimeDB.Timestamp LastSplitTime;

        public Ship(
            uint EntityId,
            uint PlayerId,
            DbQuaternion Rotation,
            DbVector3 Position,
            DbVector3 Velocity,
            DbVector3 AngularVelocity,
            SpacetimeDB.Timestamp LastSplitTime
        )
        {
            this.EntityId = EntityId;
            this.PlayerId = PlayerId;
            this.Rotation = Rotation;
            this.Position = Position;
            this.Velocity = Velocity;
            this.AngularVelocity = AngularVelocity;
            this.LastSplitTime = LastSplitTime;
        }

        public Ship()
        {
            this.Rotation = new();
            this.Position = new();
            this.Velocity = new();
            this.AngularVelocity = new();
        }
    }
}
